import 'package:flutter/material.dart';

import 'models.dart';

class DemoCatalog {
  static const student = UserProfile(
    id: 'user-sarah',
    fullName: 'Dr. Sarah Khan',
    email: 'sarah@medlearn.ai',
    track: 'NEET PG',
    role: UserRole.student,
    streakDays: 15,
    weakTopics: ['Cardiac cycle', 'Ventilator settings', 'Acid-base disorders'],
    strongTopics: ['Neuroanatomy', 'Antibiotics', 'Inflammation'],
  );

  static const admin = UserProfile(
    id: 'admin-1',
    fullName: 'MedLearn Admin',
    email: 'admin@medlearn.ai',
    track: 'MBBS',
    role: UserRole.admin,
    streakDays: 0,
    weakTopics: [],
    strongTopics: [],
  );

  static final credentials = <String, String>{
    student.email: 'Password@123',
    admin.email: 'Admin@123',
  };

  static final courses = <Course>[
    // NEET
    const Course(
      id: 'neet-physics',
      title: 'NEET Physics',
      description: '45 multiple-choice questions (MCQs) carrying 180 marks.',
      section: 'NEET',
      subject: 'Physics',
      educator: 'Dr. Expert',
      durationHours: 40,
      progressPercent: 0,
      difficulty: 'Medium',
      tags: ['NEET', 'MCQ'],
      heroIcon: Icons.science_rounded,
    ),
    const Course(
      id: 'neet-chemistry',
      title: 'NEET Chemistry',
      description: '45 MCQs carrying 180 marks.',
      section: 'NEET',
      subject: 'Chemistry',
      educator: 'Dr. Expert',
      durationHours: 40,
      progressPercent: 0,
      difficulty: 'Medium',
      tags: ['NEET', 'MCQ'],
      heroIcon: Icons.science_rounded,
    ),
    const Course(
      id: 'neet-biology',
      title: 'NEET Biology',
      description: '90 MCQs (45 in Botany and 45 in Zoology) carrying 360 marks.',
      section: 'NEET',
      subject: 'Biology',
      educator: 'Dr. Expert',
      durationHours: 80,
      progressPercent: 0,
      difficulty: 'Medium',
      tags: ['NEET', 'MCQ'],
      heroIcon: Icons.biotech_rounded,
    ),

    // 1st year
    const Course(
      id: '1st-anatomy',
      title: 'Human Anatomy',
      description: 'Core anatomy covering gross, histology, and neuroanatomy.',
      section: '1st year',
      subject: 'Anatomy',
      educator: 'Standard',
      durationHours: 60,
      progressPercent: 0,
      difficulty: 'Hard',
      tags: ['Core', 'MBBS'],
      heroIcon: Icons.accessibility_new_rounded,
    ),
    const Course(
      id: '1st-physiology',
      title: 'Medical Physiology',
      description: 'System physiology and mechanisms.',
      section: '1st year',
      subject: 'Physiology',
      educator: 'Standard',
      durationHours: 50,
      progressPercent: 0,
      difficulty: 'Medium',
      tags: ['Core', 'MBBS'],
      heroIcon: Icons.favorite_rounded,
    ),
    const Course(
      id: '1st-biochemistry',
      title: 'Biochemistry',
      description: 'Metabolic pathways and clinical correlations.',
      section: '1st year',
      subject: 'Biochemistry',
      educator: 'Standard',
      durationHours: 45,
      progressPercent: 0,
      difficulty: 'Medium',
      tags: ['Core', 'MBBS'],
      heroIcon: Icons.science_rounded,
    ),

    // 2nd year
    const Course(
      id: '2nd-forensic',
      title: 'Forensic Medicine',
      description: 'Medical jurisprudence and toxicology.',
      section: '2nd year',
      subject: 'Forensic medicine',
      educator: 'Standard',
      durationHours: 30,
      progressPercent: 0,
      difficulty: 'Medium',
      tags: ['Core', 'MBBS'],
      heroIcon: Icons.gavel_rounded,
    ),
    const Course(
      id: '2nd-community',
      title: 'Community Medicine',
      description: 'Epidemiology and public health strategies.',
      section: '2nd year',
      subject: 'Community medicine',
      educator: 'Standard',
      durationHours: 40,
      progressPercent: 0,
      difficulty: 'Medium',
      tags: ['Core', 'MBBS'],
      heroIcon: Icons.people_rounded,
    ),

    // 3rd year
    const Course(
      id: '3rd-pathology',
      title: 'Pathology',
      description: 'Disease mechanisms, structural and functional changes.',
      section: '3rd year',
      subject: 'Pathology',
      educator: 'Standard',
      durationHours: 60,
      progressPercent: 10,
      difficulty: 'Hard',
      tags: ['Core', 'MBBS'],
      heroIcon: Icons.biotech_rounded,
    ),
    const Course(
      id: '3rd-pharmacology',
      title: 'Pharmacology',
      description: 'Drug classifications, actions, and side effects.',
      section: '3rd year',
      subject: 'Pharmacology',
      educator: 'Standard',
      durationHours: 50,
      progressPercent: 0,
      difficulty: 'Hard',
      tags: ['Core', 'MBBS'],
      heroIcon: Icons.medication_rounded,
    ),
    const Course(
      id: '3rd-microbiology',
      title: 'Microbiology',
      description: 'Bacteriology, virology, immunology, and parasitology.',
      section: '3rd year',
      subject: 'Microbiology',
      educator: 'Standard',
      durationHours: 45,
      progressPercent: 0,
      difficulty: 'Medium',
      tags: ['Core', 'MBBS'],
      heroIcon: Icons.bug_report_rounded,
    ),

    // 4th year
    const Course(
      id: '4th-medicine',
      title: 'General Medicine',
      description: 'Comprehensive clinical internal medicine.',
      section: '4th year',
      subject: 'Medicine',
      educator: 'Standard',
      durationHours: 120,
      progressPercent: 0,
      difficulty: 'Hard',
      tags: ['Core', 'MBBS', 'Clinical'],
      heroIcon: Icons.health_and_safety_rounded,
    ),
    const Course(
      id: '4th-paediatrics',
      title: 'Paediatrics',
      description: 'Child health, development, and diseases.',
      section: '4th year',
      subject: 'Paediatrics',
      educator: 'Standard',
      durationHours: 40,
      progressPercent: 0,
      difficulty: 'Medium',
      tags: ['Clinical'],
      heroIcon: Icons.child_care_rounded,
    ),
    const Course(
      id: '4th-dermatology',
      title: 'Dermatology',
      description: 'Skin diseases, venerology, and leprosy.',
      section: '4th year',
      subject: 'Dermatology',
      educator: 'Standard',
      durationHours: 20,
      progressPercent: 0,
      difficulty: 'Medium',
      tags: ['Clinical'],
      heroIcon: Icons.back_hand_rounded,
    ),
    const Course(
      id: '4th-anesthesia',
      title: 'Anesthesia',
      description: 'Anesthetic procedures and critical care.',
      section: '4th year',
      subject: 'Anesthesia',
      educator: 'Standard',
      durationHours: 20,
      progressPercent: 0,
      difficulty: 'Medium',
      tags: ['Clinical'],
      heroIcon: Icons.masks_rounded,
    ),
    const Course(
      id: '4th-radiology',
      title: 'Radiology',
      description: 'Imaging techniques and clinical diagnosis.',
      section: '4th year',
      subject: 'Radiology',
      educator: 'Standard',
      durationHours: 25,
      progressPercent: 0,
      difficulty: 'Medium',
      tags: ['Clinical'],
      heroIcon: Icons.monitor_heart_rounded,
    ),
    const Course(
      id: '4th-psychiatry',
      title: 'Psychiatry',
      description: 'Mental health disorders and treatments.',
      section: '4th year',
      subject: 'Psychiatry',
      educator: 'Standard',
      durationHours: 25,
      progressPercent: 0,
      difficulty: 'Medium',
      tags: ['Clinical'],
      heroIcon: Icons.psychology_rounded,
    ),
    const Course(
      id: '4th-surgery',
      title: 'General Surgery',
      description: 'Surgical principles, trauma, and procedures.',
      section: '4th year',
      subject: 'Surgery',
      educator: 'Standard',
      durationHours: 100,
      progressPercent: 0,
      difficulty: 'Hard',
      tags: ['Core', 'MBBS', 'Clinical'],
      heroIcon: Icons.cut_rounded,
    ),
    const Course(
      id: '4th-orthopaedics',
      title: 'Orthopaedics',
      description: 'Bone fractures, joint diseases, and trauma.',
      section: '4th year',
      subject: 'Orthopaedics',
      educator: 'Standard',
      durationHours: 35,
      progressPercent: 0,
      difficulty: 'Medium',
      tags: ['Clinical'],
      heroIcon: Icons.personal_injury_rounded,
    ),
    const Course(
      id: '4th-ent',
      title: 'ENT (Otorhinolaryngology)',
      description: 'Ear, nose, and throat diseases.',
      section: '4th year',
      subject: 'Ent',
      educator: 'Standard',
      durationHours: 30,
      progressPercent: 0,
      difficulty: 'Medium',
      tags: ['Clinical'],
      heroIcon: Icons.hearing_rounded,
    ),
    const Course(
      id: '4th-ophthalmology',
      title: 'Ophthalmology',
      description: 'Eye anatomy, pathology, and vision correction.',
      section: '4th year',
      subject: 'Ophthalmology',
      educator: 'Standard',
      durationHours: 30,
      progressPercent: 0,
      difficulty: 'Medium',
      tags: ['Clinical'],
      heroIcon: Icons.remove_red_eye_rounded,
    ),
    const Course(
      id: '4th-obsgynae',
      title: 'Obstetrics & Gynaecology',
      description: 'Pregnancy, childbirth, and female reproductive health.',
      section: '4th year',
      subject: 'ObsGynae',
      educator: 'Standard',
      durationHours: 60,
      progressPercent: 0,
      difficulty: 'Hard',
      tags: ['Core', 'MBBS', 'Clinical'],
      heroIcon: Icons.pregnant_woman_rounded,
    ),
  ];

  static final modules = <CourseModule>[
    const CourseModule(
      id: 'module-ecg',
      courseId: 'course-cardiology',
      title: 'ECG Interpretation Essentials',
      summary: 'Systematic rhythm interpretation, axis, intervals, and ischemia patterns.',
      durationMinutes: 74,
      completionPercent: 100,
      kind: ContentKind.video,
    ),
    const CourseModule(
      id: 'module-heart-failure',
      courseId: 'course-cardiology',
      title: 'Heart Failure & Hemodynamics',
      summary: 'Forward failure, congestion, compensated states, and therapy ladders.',
      durationMinutes: 96,
      completionPercent: 64,
      kind: ContentKind.pdf,
    ),
    const CourseModule(
      id: 'module-cranial',
      courseId: 'course-neuro',
      title: 'Cranial Nerves Deep Dive',
      summary: 'Nuclei, lesions, reflexes, and clinical pearls.',
      durationMinutes: 82,
      completionPercent: 40,
      kind: ContentKind.video,
    ),
    const CourseModule(
      id: 'module-inflammation',
      courseId: 'course-pathology',
      title: 'Inflammation & Repair',
      summary: 'Mediators, acute vs chronic inflammation, repair sequence, and exam traps.',
      durationMinutes: 68,
      completionPercent: 75,
      kind: ContentKind.pdf,
    ),
  ];

  static final books = <LibraryBook>[
    // PRE-CLINICAL (Foundation)
    const LibraryBook(
      id: 'book-grays',
      title: 'Gray’s Anatomy for Students',
      author: 'Drake, Vogl, Mitchell',
      category: 'PRE-CLINICAL (Foundation)',
      subject: 'Anatomy',
      edition: 'Latest Edition',
      summary: 'Authoritative anatomy reference with clinical integration.',
      tags: ['Core', 'Classic', 'Anatomy'],
    ),
    const LibraryBook(
      id: 'book-moore',
      title: 'Clinically Oriented Anatomy',
      author: 'Moore & Dalley',
      category: 'PRE-CLINICAL (Foundation)',
      subject: 'Anatomy',
      edition: 'Latest Edition',
      summary: 'Highly detailed clinically oriented anatomy textbook.',
      tags: ['Clinical', 'Anatomy'],
    ),
    const LibraryBook(
      id: 'book-chaurasia',
      title: 'B.D. Chaurasia’s Human Anatomy (volumes)',
      author: 'B.D. Chaurasia',
      category: 'PRE-CLINICAL (Foundation)',
      subject: 'Anatomy',
      edition: 'Latest Edition',
      summary: 'Popular Indian alternative for anatomy foundation.',
      tags: ['Alternative', 'Anatomy'],
    ),
    const LibraryBook(
      id: 'book-guyton',
      title: 'Guyton & Hall Textbook of Medical Physiology',
      author: 'John E. Hall',
      category: 'PRE-CLINICAL (Foundation)',
      subject: 'Physiology',
      edition: '14th Edition',
      summary: 'Gold standard physiology text for fundamentals and exams.',
      tags: ['Gold Standard', 'Physiology'],
    ),
    const LibraryBook(
      id: 'book-ganong',
      title: 'Ganong’s Review of Medical Physiology',
      author: 'Kim E. Barrett et al.',
      category: 'PRE-CLINICAL (Foundation)',
      subject: 'Physiology',
      edition: 'Latest Edition',
      summary: 'Excellent review of physiology with key concepts.',
      tags: ['Review', 'Physiology'],
    ),
    const LibraryBook(
      id: 'book-harper',
      title: 'Harper’s Illustrated Biochemistry',
      author: 'Victor W. Rodwell et al.',
      category: 'PRE-CLINICAL (Foundation)',
      subject: 'Biochemistry',
      edition: 'Latest Edition',
      summary: 'Detailed biochemistry principles.',
      tags: ['Core', 'Biochemistry'],
    ),
    const LibraryBook(
      id: 'book-lippincott',
      title: 'Lippincott’s Biochemistry',
      author: 'Denise R. Ferrier',
      category: 'PRE-CLINICAL (Foundation)',
      subject: 'Biochemistry',
      edition: 'Latest Edition',
      summary: 'Illustrated, exam-focused biochemistry insights.',
      tags: ['Review', 'Biochemistry'],
    ),
    // PARA-CLINICAL (Core Concepts)
    const LibraryBook(
      id: "book-robbins",
      title: "Robbins & Cotran Pathologic Basis of Disease",
      author: "Kumar, Abbas, Aster",
      category: "PARA-CLINICAL (Core Concepts)",
      subject: "Pathology",
      edition: "Latest Edition",
      summary: "The gold standard for pathology.",
      tags: ["Gold Standard", "Pathology"],
    ),
    const LibraryBook(
      id: "book-robbins-basic",
      title: "Basic Pathology",
      author: "Kumar, Abbas & Aster",
      category: "PARA-CLINICAL (Core Concepts)",
      subject: "Pathology",
      edition: "Latest Edition",
      summary: "Short version of pathology basis.",
      tags: ["Short version", "Pathology"],
    ),
    const LibraryBook(
      id: "book-goljian",
      title: "Rapid Review Pathology",
      author: "Goljian",
      category: "PARA-CLINICAL (Core Concepts)",
      subject: "Pathology",
      edition: "Latest Edition",
      summary: "High-yield review for rapid revision.",
      tags: ["High-yield", "Pathology"],
    ),
    const LibraryBook(
      id: "book-murray",
      title: "Murray’s Medical Microbiology",
      author: "Patrick R. Murray",
      category: "PARA-CLINICAL (Core Concepts)",
      subject: "Microbiology",
      edition: "Latest Edition",
      summary: "Comprehensive medical microbiology.",
      tags: ["Core", "Microbiology"],
    ),
    const LibraryBook(
      id: "book-jawetz",
      title: "Jawetz, Melnick & Adelberg’s Medical Microbiology",
      author: "Geo. F. Brooks et al.",
      category: "PARA-CLINICAL (Core Concepts)",
      subject: "Microbiology",
      edition: "Latest Edition",
      summary: "Classic text on medical microbiology.",
      tags: ["Classic", "Microbiology"],
    ),
    const LibraryBook(
      id: "book-katzung",
      title: "Katzung & Trevor’s Pharmacology",
      author: "Bertram G. Katzung",
      category: "PARA-CLINICAL (Core Concepts)",
      subject: "Pharmacology",
      edition: "Latest Edition",
      summary: "Excellent pharmacology review and text.",
      tags: ["Core", "Pharmacology"],
    ),
    const LibraryBook(
      id: "book-brunton",
      title: "Basic & Clinical Pharmacology",
      author: "Brunton",
      category: "PARA-CLINICAL (Core Concepts)",
      subject: "Pharmacology",
      edition: "Latest Edition",
      summary: "Standard text for clinical pharmacology.",
      tags: ["Clinical", "Pharmacology"],
    ),
    // PARA-CLINICAL / CLINICAL TRANSITION
    const LibraryBook(
      id: "book-reddy",
      title: "Essentials of Forensic Medicine & Toxicology",
      author: "Reddy & Murthy",
      category: "PARA-CLINICAL / CLINICAL TRANSITION",
      subject: "Forensic Medicine & Toxicology (FMT)",
      edition: "Latest Edition",
      summary: "Comprehensive forensic medicine and toxicology.",
      tags: ["FMT", "Forensic", "Toxicology"],
    ),
    const LibraryBook(
      id: "book-narayan-reddy",
      title: "Textbook of Forensic Medicine",
      author: "K.S. Narayan Reddy",
      category: "PARA-CLINICAL / CLINICAL TRANSITION",
      subject: "Forensic Medicine & Toxicology (FMT)",
      edition: "Latest Edition",
      summary: "Alternative textbook of forensic medicine.",
      tags: ["Alternative", "FMT"],
    ),
    const LibraryBook(
      id: "book-park",
      title: "Park’s Textbook of Preventive & Social Medicine",
      author: "K. Park",
      category: "PARA-CLINICAL / CLINICAL TRANSITION",
      subject: "PSM (Preventive & Social Medicine)",
      edition: "Latest Edition",
      summary: "The gold standard for preventive and social medicine.",
      tags: ["Core", "PSM", "Community Medicine"],
    ),
    // CLINICAL CORE
    const LibraryBook(
      id: "book-harrison",
      title: "Harrison's Principles of Internal Medicine",
      author: "J. Larry Jameson",
      category: "CLINICAL CORE",
      subject: "Medicine",
      edition: "21st Edition",
      summary: "Comprehensive medicine text with system-wise disease reviews.",
      tags: ["Medicine", "Clinical"],
    ),
    const LibraryBook(
      id: "book-stepup",
      title: "Step-Up to Medicine / Pocket Medicine",
      author: "Various",
      category: "CLINICAL CORE",
      subject: "Medicine",
      edition: "Latest Edition",
      summary: "Exam-friendly and quick review for medicine.",
      tags: ["Exam-friendly", "Medicine"],
    ),
    const LibraryBook(
      id: "book-schwartz",
      title: "Schwartz’s Principles of Surgery",
      author: "F. Charles Brunicardi",
      category: "CLINICAL CORE",
      subject: "Surgery",
      edition: "Latest Edition",
      summary: "Comprehensive surgical principles.",
      tags: ["Surgery", "Core"],
    ),
    const LibraryBook(
      id: "book-bailey",
      title: "Bailey & Love’s Short Practice of Surgery",
      author: "Norman Williams et al.",
      category: "CLINICAL CORE",
      subject: "Surgery",
      edition: "Latest Edition",
      summary: "Classic text focusing on standard practice of surgery.",
      tags: ["Classic", "Surgery"],
    ),
    const LibraryBook(
      id: "book-williams-ob",
      title: "Williams Obstetrics",
      author: "F. Gary Cunningham et al.",
      category: "CLINICAL CORE",
      subject: "Obstetrics & Gynecology",
      edition: "Latest Edition",
      summary: "Gold standard reference for obstetrics.",
      tags: ["Obstetrics", "OBGYN"],
    ),
    const LibraryBook(
      id: "book-dutta",
      title: "Dutta’s Textbook of Obstetrics",
      author: "D.C. Dutta",
      category: "CLINICAL CORE",
      subject: "Obstetrics & Gynecology",
      edition: "Latest Edition",
      summary: "Very widely read and student-friendly text.",
      tags: ["Obstetrics"],
    ),
    const LibraryBook(
      id: "book-williams-gyn",
      title: "Williams Gynecology / Shaw’s Textbook of Gynecology",
      author: "Hoffman et al.",
      category: "CLINICAL CORE",
      subject: "Obstetrics & Gynecology",
      edition: "Latest Edition",
      summary: "Extensive text detailing gynecological practices.",
      tags: ["Gynecology"],
    ),
    // SPECIALTY CLINICAL
    const LibraryBook(
      id: "book-cummings",
      title: "Cummings Otolaryngology — Head & Neck Surgery",
      author: "Paul W. Flint et al.",
      category: "SPECIALTY CLINICAL",
      subject: "ENT (Otorhinolaryngology)",
      edition: "Latest Edition",
      summary: "Foremost text on ENT and head & neck surgery.",
      tags: ["ENT", "Surgery"],
    ),
    const LibraryBook(
      id: "book-ent-glance",
      title: "ENT at a Glance",
      author: "Nazia Munir et al.",
      category: "SPECIALTY CLINICAL",
      subject: "ENT (Otorhinolaryngology)",
      edition: "Latest Edition",
      summary: "Rapid review of ENT.",
      tags: ["Review", "ENT"],
    ),
    const LibraryBook(
      id: "book-parsons",
      title: "Parson’s Diseases of the Eye",
      author: "Sihota & Tandon",
      category: "SPECIALTY CLINICAL",
      subject: "Ophthalmology",
      edition: "Latest Edition",
      summary: "Core textbook for ophthalmic study.",
      tags: ["Ophthalmology"],
    ),
    const LibraryBook(
      id: "book-vaughan",
      title: "Vaughan & Asbury’s General Ophthalmology",
      author: "Paul Riordan-Eva",
      category: "SPECIALTY CLINICAL",
      subject: "Ophthalmology",
      edition: "Latest Edition",
      summary: "Essentials for general ophthalmology.",
      tags: ["Essentials", "Ophthalmology"],
    ),
    const LibraryBook(
      id: "book-campbell",
      title: "Campbell’s Operative Orthopaedics",
      author: "Frederick M. Azar et al.",
      category: "SPECIALTY CLINICAL",
      subject: "Orthopedics",
      edition: "Latest Edition",
      summary: "Unparalleled resource on operative orthopedics.",
      tags: ["Orthopedics", "Surgery"],
    ),
    const LibraryBook(
      id: "book-saha",
      title: "Orthopaedics, Trauma & Rheumatology",
      author: "A.K. Saha",
      category: "SPECIALTY CLINICAL",
      subject: "Orthopedics",
      edition: "Latest Edition",
      summary: "Thorough textbook for orthopedics and trauma.",
      tags: ["Textbook", "Orthopaedics"],
    ),
    const LibraryBook(
      id: "book-miller",
      title: "Miller’s Anesthesia",
      author: "Michael A. Gropper",
      category: "SPECIALTY CLINICAL",
      subject: "Anesthesia",
      edition: "Latest Edition",
      summary: "Definitive text for anesthesia principles.",
      tags: ["Anesthesia"],
    ),
    const LibraryBook(
      id: "book-stoelting",
      title: "Stoelting’s Pharmacology & Physiology in Anesthetic Practice",
      author: "Pamela Flood et al.",
      category: "SPECIALTY CLINICAL",
      subject: "Anesthesia",
      edition: "Latest Edition",
      summary: "Clinical basics for anesthetic pharmacology and physiology.",
      tags: ["Clinical", "Anesthesia"],
    ),
    const LibraryBook(
      id: "book-kaplan",
      title: "Kaplan & Sadock’s Synopsis of Psychiatry",
      author: "Benjamin J. Sadock et al.",
      category: "SPECIALTY CLINICAL",
      subject: "Psychiatry",
      edition: "Latest Edition",
      summary: "Extensive resource on behavioral sciences and psychiatry.",
      tags: ["Psychiatry", "Behavioral"],
    ),
    const LibraryBook(
      id: "book-kulhara",
      title: "Textbook of Psychiatry",
      author: "Kulhara / Trzepacz & Baker",
      category: "SPECIALTY CLINICAL",
      subject: "Psychiatry",
      edition: "Latest Edition",
      summary: "Alternative learning structure for psychiatry text.",
      tags: ["Alternative", "Psychiatry"],
    ),
  ];

  static final quizzes = <QuizSummary>[
    const QuizSummary(
      id: 'quiz-cardiology',
      title: 'Cardiovascular Systems Drill',
      description: 'Timed practice focused on cardiology concepts and clinical reasoning.',
      subject: 'Medicine',
      examTrack: 'NEET PG',
      durationMinutes: 85,
      totalQuestions: 6,
      topicFocus: ['Cardiac cycle', 'Heart sounds', 'Shock', 'Valvular disease'],
    ),
    const QuizSummary(
      id: 'quiz-pathology',
      title: 'Inflammation & Repair Sprint',
      description: 'Rapid pathology revision with explanation-first feedback.',
      subject: 'Pathology',
      examTrack: 'MBBS',
      durationMinutes: 35,
      totalQuestions: 4,
      topicFocus: ['Inflammation', 'Mediators', 'Repair'],
    ),
    const QuizSummary(
      id: 'quiz-pulm',
      title: 'USMLE Pulmonology High-Yield MCQs',
      description: 'Step-style questions on pneumonia, ARDS, and respiratory support.',
      subject: 'Medicine',
      examTrack: 'USMLE',
      durationMinutes: 45,
      totalQuestions: 4,
      topicFocus: ['Pneumonia', 'ARDS', 'Ventilator settings'],
    ),
  ];

  static final questions = <QuizQuestion>[
    QuizQuestion(
      id: 'q1',
      quizId: 'quiz-cardiology',
      subject: 'Medicine',
      topic: 'Cardiac cycle',
      prompt: 'Which of the following events occurs during isovolumetric contraction?',
      explanation: 'Both mitral and aortic valves are closed, so pressure rises with no volume change.',
      correctOptionId: 'q1-b',
      options: const [
        QuizOption(id: 'q1-a', label: 'A', text: 'Rapid ventricular filling'),
        QuizOption(id: 'q1-b', label: 'B', text: 'Rise in ventricular pressure at constant volume'),
        QuizOption(id: 'q1-c', label: 'C', text: 'Opening of semilunar valves'),
        QuizOption(id: 'q1-d', label: 'D', text: 'Atrial contraction'),
      ],
    ),
    QuizQuestion(
      id: 'q2',
      quizId: 'quiz-cardiology',
      subject: 'Medicine',
      topic: 'Valvular disease',
      prompt: 'A mid-diastolic murmur with opening snap is most suggestive of:',
      explanation: 'The classic auscultatory finding is mitral stenosis.',
      correctOptionId: 'q2-a',
      options: const [
        QuizOption(id: 'q2-a', label: 'A', text: 'Mitral stenosis'),
        QuizOption(id: 'q2-b', label: 'B', text: 'Aortic regurgitation'),
        QuizOption(id: 'q2-c', label: 'C', text: 'Mitral regurgitation'),
        QuizOption(id: 'q2-d', label: 'D', text: 'Aortic stenosis'),
      ],
    ),
    QuizQuestion(
      id: 'q3',
      quizId: 'quiz-cardiology',
      subject: 'Medicine',
      topic: 'Shock',
      prompt: 'The most likely hemodynamic profile in septic shock is:',
      explanation: 'Septic shock typically presents with low SVR and high cardiac output in the warm phase.',
      correctOptionId: 'q3-c',
      options: const [
        QuizOption(id: 'q3-a', label: 'A', text: 'High SVR, low cardiac output'),
        QuizOption(id: 'q3-b', label: 'B', text: 'High SVR, high cardiac output'),
        QuizOption(id: 'q3-c', label: 'C', text: 'Low SVR, high cardiac output'),
        QuizOption(id: 'q3-d', label: 'D', text: 'Normal SVR, low preload'),
      ],
    ),
    QuizQuestion(
      id: 'q4',
      quizId: 'quiz-cardiology',
      subject: 'Medicine',
      topic: 'Heart sounds',
      prompt: 'A fixed split S2 is classically associated with:',
      explanation: 'Atrial septal defect causes fixed splitting of the second heart sound.',
      correctOptionId: 'q4-d',
      options: const [
        QuizOption(id: 'q4-a', label: 'A', text: 'Pulmonary hypertension'),
        QuizOption(id: 'q4-b', label: 'B', text: 'Aortic stenosis'),
        QuizOption(id: 'q4-c', label: 'C', text: 'Mitral valve prolapse'),
        QuizOption(id: 'q4-d', label: 'D', text: 'Atrial septal defect'),
      ],
    ),
    QuizQuestion(
      id: 'q5',
      quizId: 'quiz-pulm',
      subject: 'Medicine',
      topic: 'Pneumonia',
      prompt: 'The most common cause of community-acquired pneumonia is:',
      explanation: 'Streptococcus pneumoniae remains the classic answer for typical CAP.',
      correctOptionId: 'q5-a',
      options: const [
        QuizOption(id: 'q5-a', label: 'A', text: 'Streptococcus pneumoniae'),
        QuizOption(id: 'q5-b', label: 'B', text: 'Mycoplasma pneumoniae'),
        QuizOption(id: 'q5-c', label: 'C', text: 'Haemophilus influenzae'),
        QuizOption(id: 'q5-d', label: 'D', text: 'Staphylococcus aureus'),
      ],
    ),
    QuizQuestion(
      id: 'q6',
      quizId: 'quiz-pulm',
      subject: 'Medicine',
      topic: 'ARDS',
      prompt: 'A key pathologic feature of ARDS is:',
      explanation: 'Diffuse alveolar damage with hyaline membrane formation defines ARDS.',
      correctOptionId: 'q6-b',
      options: const [
        QuizOption(id: 'q6-a', label: 'A', text: 'Pleural fibrosis'),
        QuizOption(id: 'q6-b', label: 'B', text: 'Diffuse alveolar damage'),
        QuizOption(id: 'q6-c', label: 'C', text: 'Bronchial smooth muscle hypertrophy'),
        QuizOption(id: 'q6-d', label: 'D', text: 'Caseating granulomas'),
      ],
    ),
    QuizQuestion(
      id: 'q7',
      quizId: 'quiz-pathology',
      subject: 'Pathology',
      topic: 'Inflammation',
      prompt: 'The first cells to arrive in acute inflammation are usually:',
      explanation: 'Neutrophils dominate the early phase of acute inflammation.',
      correctOptionId: 'q7-a',
      options: const [
        QuizOption(id: 'q7-a', label: 'A', text: 'Neutrophils'),
        QuizOption(id: 'q7-b', label: 'B', text: 'Lymphocytes'),
        QuizOption(id: 'q7-c', label: 'C', text: 'Eosinophils'),
        QuizOption(id: 'q7-d', label: 'D', text: 'Fibroblasts'),
      ],
    ),
    QuizQuestion(
      id: 'q8',
      quizId: 'quiz-pathology',
      subject: 'Pathology',
      topic: 'Repair',
      prompt: 'Granulation tissue is characterized by:',
      explanation: 'Granulation tissue contains proliferating capillaries and fibroblasts.',
      correctOptionId: 'q8-d',
      options: const [
        QuizOption(id: 'q8-a', label: 'A', text: 'Dense collagen and scarce vessels'),
        QuizOption(id: 'q8-b', label: 'B', text: 'Hyalinized scar only'),
        QuizOption(id: 'q8-c', label: 'C', text: 'Caseous necrosis'),
        QuizOption(id: 'q8-d', label: 'D', text: 'New capillaries and fibroblasts'),
      ],
    ),
  ];

  static final recommendations = <RecommendationItem>[
    const RecommendationItem(
      id: 'rec-1',
      title: 'Rebuild your cardiac cycle foundation',
      description: 'You miss pressure-volume and valve timing questions under time pressure.',
      topic: 'Cardiac cycle',
      priorityLabel: 'High priority',
    ),
    const RecommendationItem(
      id: 'rec-2',
      title: 'Schedule a 20-minute ventilator revision',
      description: 'Respiratory support questions are trending below your baseline.',
      topic: 'Ventilator settings',
      priorityLabel: 'Medium priority',
    ),
    const RecommendationItem(
      id: 'rec-3',
      title: 'Lean into neuroanatomy momentum',
      description: 'Convert your strongest subject into spaced revision points this week.',
      topic: 'Neuroanatomy',
      priorityLabel: 'Low priority',
    ),
  ];

  static final notifications = <NotificationItem>[
    const NotificationItem(
      title: 'Mock NEET PG Simulation',
      message: 'Your full-length simulation starts Saturday at 9:00 AM.',
      relativeTime: '2h ago',
    ),
    const NotificationItem(
      title: 'AI recommendation ready',
      message: 'Cardiac cycle and ventilator settings were added to your focus stack.',
      relativeTime: 'Today',
    ),
  ];

  static final insights = <PerformanceInsight>[
    const PerformanceInsight(label: 'Accuracy', value: '78%', trend: '+6% week-on-week'),
    const PerformanceInsight(label: 'Study hours', value: '12.4', trend: '+8% this week'),
    const PerformanceInsight(label: 'Quiz velocity', value: '42s', trend: '5s faster'),
    const PerformanceInsight(label: 'Consistency', value: '88%', trend: '+12% month-on-month'),
  ];

  static List<CourseModule> modulesForCourse(String courseId) {
    return modules.where((module) => module.courseId == courseId).toList();
  }

  static List<QuizQuestion> questionsForQuiz(String quizId) {
    return questions.where((question) => question.quizId == quizId).toList();
  }

  static List<StudyTask> seedTasks(String userId) {
    final now = DateTime.now();
    return [
      StudyTask(
        id: 'task-1',
        userId: userId,
        title: 'Review Physiology',
        description: 'Cardiac cycle and pressure-volume loops',
        scheduledFor: DateTime(now.year, now.month, now.day, 9, 0),
        category: TaskCategory.revision,
        status: TaskStatus.todo,
      ),
      StudyTask(
        id: 'task-2',
        userId: userId,
        title: '15 MCQs in Pathology',
        description: 'Focus on neoplasia and inflammation',
        scheduledFor: DateTime(now.year, now.month, now.day, 11, 0),
        category: TaskCategory.quiz,
        status: TaskStatus.inProgress,
      ),
      StudyTask(
        id: 'task-3',
        userId: userId,
        title: 'Watch ECG Lecture',
        description: 'Module 4: arrhythmias and conduction blocks',
        scheduledFor: DateTime(now.year, now.month, now.day, 14, 0),
        category: TaskCategory.course,
        status: TaskStatus.todo,
      ),
    ];
  }

  static List<QuizAttempt> seedAttempts(String userId) {
    return [
      QuizAttempt(
        id: 'attempt-1',
        quizId: 'quiz-cardiology',
        userId: userId,
        score: 83,
        accuracy: 83,
        durationSeconds: 3840,
        submittedAt: DateTime.now().subtract(const Duration(days: 3)),
        weakTopics: const ['Cardiac cycle'],
        strongTopics: const ['Valvular disease', 'Shock'],
      ),
    ];
  }

  static List<ChatMessage> seedMessages() {
    return [
      ChatMessage(
        id: 'm1',
        text: 'You were strongest in anatomy this week. If we focus on cardiac cycle today, I can generate a 25-minute revision block plus 10 custom MCQs.',
        isUser: false,
        timestamp: DateTime.now().subtract(const Duration(minutes: 20)),
      ),
      ChatMessage(
        id: 'm2',
        text: 'Why is isovolumetric contraction tested so often?',
        isUser: true,
        timestamp: DateTime.now().subtract(const Duration(minutes: 18)),
      ),
      ChatMessage(
        id: 'm3',
        text: 'Because it links valve state, pressure change, and volume change in one step. It is a favorite integration point for physiology questions.',
        isUser: false,
        timestamp: DateTime.now().subtract(const Duration(minutes: 17)),
      ),
    ];
  }

  static UserProgress progressFor(UserProfile user, List<QuizAttempt> attempts) {
    final relevantAttempts = attempts.where((attempt) => attempt.userId == user.id).toList();
    final averageAccuracy = relevantAttempts.isEmpty
        ? 0
        : (relevantAttempts.map((attempt) => attempt.accuracy).reduce((a, b) => a + b) / relevantAttempts.length).round();

    return UserProgress(
      completionPercent: user.role == UserRole.admin ? 100 : 72,
      hoursLearned: user.role == UserRole.admin ? 0 : 126.0,
      quizzesTaken: relevantAttempts.length,
      averageAccuracy: averageAccuracy,
      weakTopics: user.weakTopics,
      strongTopics: user.strongTopics,
      insights: insights,
    );
  }

  static UserProfile? authenticate(String email, String password) {
    final normalized = email.trim().toLowerCase();
    final expected = credentials[normalized];

    if (expected == null || expected != password) {
      return null;
    }

    if (normalized == student.email) {
      return student;
    }

    if (normalized == admin.email) {
      return admin;
    }

    return null;
  }
}
