import type {
  AIRecommendation,
  AnalyticsInsight,
  Book,
  ChatMessage,
  Course,
  DashboardPayload,
  Module,
  Note,
  PdfResource,
  ProgressSnapshot,
  Question,
  Quiz,
  QuizAttempt,
  StudyPlan,
  StudyTask,
  User,
  UserNotification,
  VideoResource,
} from "./types.js";

export const users: User[] = [
  {
    id: "user-sarah",
    fullName: "Dr. Sarah Khan",
    email: "sarah@medlearn.ai",
    role: "student",
    examTrack: "NEET_PG",
    avatarUrl:
      "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=400&q=80",
    streakDays: 15,
    weakTopics: ["Cardiac cycle", "Ventilator settings", "Acid-base disorders"],
    strongTopics: ["Neuroanatomy", "Respiratory pathology", "Antibiotics"],
    createdAt: "2026-01-05T09:00:00.000Z",
  },
  {
    id: "admin-1",
    fullName: "MedLearn Admin",
    email: "admin@medlearn.ai",
    role: "admin",
    examTrack: "MBBS",
    streakDays: 0,
    weakTopics: [],
    strongTopics: [],
    createdAt: "2025-10-01T00:00:00.000Z",
  },
];

export const courses: Course[] = [
  // NEET
  {
    id: "neet-physics",
    slug: "neet-physics",
    title: "NEET Physics",
    description: "45 multiple-choice questions (MCQs) carrying 180 marks.",
    section: "NEET",
    subject: "Physics",
    difficulty: "medium",
    durationHours: 40,
    educator: "Dr. Expert",
    thumbnailUrl: "https://images.unsplash.com/photo-1632516643720-e7f5d7d6ecc9?auto=format&fit=crop&w=400&q=80",
    progressPercent: 0,
    enrolledStudents: 1542,
    tags: ["NEET", "MCQ"],
  },
  {
    id: "neet-chemistry",
    slug: "neet-chemistry",
    title: "NEET Chemistry",
    description: "45 MCQs carrying 180 marks.",
    section: "NEET",
    subject: "Chemistry",
    difficulty: "medium",
    durationHours: 40,
    educator: "Dr. Expert",
    thumbnailUrl: "https://images.unsplash.com/photo-1603126857599-f6e15782fd5d?auto=format&fit=crop&w=400&q=80",
    progressPercent: 0,
    enrolledStudents: 1421,
    tags: ["NEET", "MCQ"],
  },
  {
    id: "neet-biology",
    slug: "neet-biology",
    title: "NEET Biology",
    description: "90 MCQs (45 in Botany and 45 in Zoology) carrying 360 marks.",
    section: "NEET",
    subject: "Biology",
    difficulty: "medium",
    durationHours: 80,
    educator: "Dr. Expert",
    thumbnailUrl: "https://images.unsplash.com/photo-1530213786676-412bd6711718?auto=format&fit=crop&w=400&q=80",
    progressPercent: 0,
    enrolledStudents: 2311,
    tags: ["NEET", "MCQ"],
  },

  // 1st year
  {
    id: "1st-anatomy",
    slug: "human-anatomy",
    title: "Human Anatomy",
    description: "Core anatomy covering gross, histology, and neuroanatomy.",
    section: "1st year",
    subject: "Anatomy",
    difficulty: "hard",
    durationHours: 60,
    educator: "Standard",
    thumbnailUrl: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=400&q=80",
    progressPercent: 0,
    enrolledStudents: 5020,
    tags: ["Core", "MBBS"],
  },
  {
    id: "1st-physiology",
    slug: "medical-physiology",
    title: "Medical Physiology",
    description: "System physiology and mechanisms.",
    section: "1st year",
    subject: "Physiology",
    difficulty: "medium",
    durationHours: 50,
    educator: "Standard",
    thumbnailUrl: "https://images.unsplash.com/photo-1530497610245-94d3c16cda28?auto=format&fit=crop&w=400&q=80",
    progressPercent: 0,
    enrolledStudents: 4901,
    tags: ["Core", "MBBS"],
  },
  {
    id: "1st-biochemistry",
    slug: "biochemistry",
    title: "Biochemistry",
    description: "Metabolic pathways and clinical correlations.",
    section: "1st year",
    subject: "Biochemistry",
    difficulty: "medium",
    durationHours: 45,
    educator: "Standard",
    thumbnailUrl: "https://images.unsplash.com/photo-1579154204601-01588f351e67?auto=format&fit=crop&w=400&q=80",
    progressPercent: 0,
    enrolledStudents: 4210,
    tags: ["Core", "MBBS"],
  },

  // 2nd year
  {
    id: "2nd-forensic",
    slug: "forensic-medicine",
    title: "Forensic Medicine",
    description: "Medical jurisprudence and toxicology.",
    section: "2nd year",
    subject: "Forensic medicine",
    difficulty: "medium",
    durationHours: 30,
    educator: "Standard",
    thumbnailUrl: "https://images.unsplash.com/photo-1581056771107-24ca5f033842?auto=format&fit=crop&w=400&q=80",
    progressPercent: 0,
    enrolledStudents: 3102,
    tags: ["Core", "MBBS"],
  },
  {
    id: "2nd-community",
    slug: "community-medicine",
    title: "Community Medicine",
    description: "Epidemiology and public health strategies.",
    section: "2nd year",
    subject: "Community medicine",
    difficulty: "medium",
    durationHours: 40,
    educator: "Standard",
    thumbnailUrl: "https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?auto=format&fit=crop&w=400&q=80",
    progressPercent: 0,
    enrolledStudents: 3801,
    tags: ["Core", "MBBS"],
  },

  // 3rd year
  {
    id: "3rd-pathology",
    slug: "pathology",
    title: "Pathology",
    description: "Disease mechanisms, structural and functional changes.",
    section: "3rd year",
    subject: "Pathology",
    difficulty: "hard",
    durationHours: 60,
    educator: "Standard",
    thumbnailUrl: "https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=400&q=80",
    progressPercent: 0,
    enrolledStudents: 6112,
    tags: ["Core", "MBBS"],
  },
  {
    id: "3rd-pharmacology",
    slug: "pharmacology",
    title: "Pharmacology",
    description: "Drug classifications, actions, and side effects.",
    section: "3rd year",
    subject: "Pharmacology",
    difficulty: "hard",
    durationHours: 50,
    educator: "Standard",
    thumbnailUrl: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?auto=format&fit=crop&w=400&q=80",
    progressPercent: 0,
    enrolledStudents: 5934,
    tags: ["Core", "MBBS"],
  },
  {
    id: "3rd-microbiology",
    slug: "microbiology",
    title: "Microbiology",
    description: "Bacteriology, virology, immunology, and parasitology.",
    section: "3rd year",
    subject: "Microbiology",
    difficulty: "medium",
    durationHours: 45,
    educator: "Standard",
    thumbnailUrl: "https://images.unsplash.com/photo-1584036561566-baf8f5f1b144?auto=format&fit=crop&w=400&q=80",
    progressPercent: 0,
    enrolledStudents: 5412,
    tags: ["Core", "MBBS"],
  },

  // 4th year
  {
    id: "4th-medicine",
    slug: "general-medicine",
    title: "General Medicine",
    description: "Comprehensive clinical internal medicine.",
    section: "4th year",
    subject: "Medicine",
    difficulty: "hard",
    durationHours: 120,
    educator: "Standard",
    thumbnailUrl: "https://images.unsplash.com/photo-1505751172876-fa1923c5c528?auto=format&fit=crop&w=400&q=80",
    progressPercent: 0,
    enrolledStudents: 8123,
    tags: ["Core", "MBBS", "Clinical"],
  },
  {
    id: "4th-paediatrics",
    slug: "paediatrics",
    title: "Paediatrics",
    description: "Child health, development, and diseases.",
    section: "4th year",
    subject: "Paediatrics",
    difficulty: "medium",
    durationHours: 40,
    educator: "Standard",
    thumbnailUrl: "https://images.unsplash.com/photo-1519500528352-2d1460418d41?auto=format&fit=crop&w=400&q=80",
    progressPercent: 0,
    enrolledStudents: 4120,
    tags: ["Clinical"],
  },
  {
    id: "4th-dermatology",
    slug: "dermatology",
    title: "Dermatology",
    description: "Skin diseases, venerology, and leprosy.",
    section: "4th year",
    subject: "Dermatology",
    difficulty: "medium",
    durationHours: 20,
    educator: "Standard",
    thumbnailUrl: "https://images.unsplash.com/photo-1612443015486-da7565c82910?auto=format&fit=crop&w=400&q=80",
    progressPercent: 0,
    enrolledStudents: 3125,
    tags: ["Clinical"],
  },
  {
    id: "4th-anesthesia",
    slug: "anesthesia",
    title: "Anesthesia",
    description: "Anesthetic procedures and critical care.",
    section: "4th year",
    subject: "Anesthesia",
    difficulty: "medium",
    durationHours: 20,
    educator: "Standard",
    thumbnailUrl: "https://images.unsplash.com/photo-1551076805-e1869033e561?auto=format&fit=crop&w=400&q=80",
    progressPercent: 0,
    enrolledStudents: 2984,
    tags: ["Clinical"],
  },
  {
    id: "4th-radiology",
    slug: "radiology",
    title: "Radiology",
    description: "Imaging techniques and clinical diagnosis.",
    section: "4th year",
    subject: "Radiology",
    difficulty: "medium",
    durationHours: 25,
    educator: "Standard",
    thumbnailUrl: "https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&w=400&q=80",
    progressPercent: 0,
    enrolledStudents: 3452,
    tags: ["Clinical"],
  },
  {
    id: "4th-psychiatry",
    slug: "psychiatry",
    title: "Psychiatry",
    description: "Mental health disorders and treatments.",
    section: "4th year",
    subject: "Psychiatry",
    difficulty: "medium",
    durationHours: 25,
    educator: "Standard",
    thumbnailUrl: "https://images.unsplash.com/photo-1527613426441-4da17471b66d?auto=format&fit=crop&w=400&q=80",
    progressPercent: 0,
    enrolledStudents: 3211,
    tags: ["Clinical"],
  },
  {
    id: "4th-surgery",
    slug: "general-surgery",
    title: "General Surgery",
    description: "Surgical principles, trauma, and procedures.",
    section: "4th year",
    subject: "Surgery",
    difficulty: "hard",
    durationHours: 100,
    educator: "Standard",
    thumbnailUrl: "https://images.unsplash.com/photo-1551076805-e1869033e561?auto=format&fit=crop&w=400&q=80",
    progressPercent: 0,
    enrolledStudents: 6542,
    tags: ["Core", "MBBS", "Clinical"],
  },
  {
    id: "4th-orthopaedics",
    slug: "orthopaedics",
    title: "Orthopaedics",
    description: "Bone fractures, joint diseases, and trauma.",
    section: "4th year",
    subject: "Orthopaedics",
    difficulty: "medium",
    durationHours: 35,
    educator: "Standard",
    thumbnailUrl: "https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=400&q=80",
    progressPercent: 0,
    enrolledStudents: 4125,
    tags: ["Clinical"],
  },
  {
    id: "4th-ent",
    slug: "ent",
    title: "ENT (Otorhinolaryngology)",
    description: "Ear, nose, and throat diseases.",
    section: "4th year",
    subject: "Ent",
    difficulty: "medium",
    durationHours: 30,
    educator: "Standard",
    thumbnailUrl: "https://images.unsplash.com/photo-1584362917165-526a968579e8?auto=format&fit=crop&w=400&q=80",
    progressPercent: 0,
    enrolledStudents: 3412,
    tags: ["Clinical"],
  },
  {
    id: "4th-ophthalmology",
    slug: "ophthalmology",
    title: "Ophthalmology",
    description: "Eye anatomy, pathology, and vision correction.",
    section: "4th year",
    subject: "Ophthalmology",
    difficulty: "medium",
    durationHours: 30,
    educator: "Standard",
    thumbnailUrl: "https://images.unsplash.com/photo-1589828555909-6d63ef2fc610?auto=format&fit=crop&w=400&q=80",
    progressPercent: 0,
    enrolledStudents: 3671,
    tags: ["Clinical"],
  },
  {
    id: "4th-obsgynae",
    slug: "obstetrics-gynaecology",
    title: "Obstetrics & Gynaecology",
    description: "Pregnancy, childbirth, and female reproductive health.",
    section: "4th year",
    subject: "ObsGynae",
    difficulty: "hard",
    durationHours: 60,
    educator: "Standard",
    thumbnailUrl: "https://images.unsplash.com/photo-1580482594689-d9313ab7774e?auto=format&fit=crop&w=400&q=80",
    progressPercent: 0,
    enrolledStudents: 5214,
    tags: ["Clinical", "MBBS"],
  },
];

export const modules: Module[] = [
  {
    id: "module-ecg",
    courseId: "course-cardiology",
    title: "ECG Interpretation Essentials",
    summary: "Systematic rhythm interpretation, axis, and ischemia patterns.",
    durationMinutes: 74,
    orderIndex: 1,
    completionPercent: 100,
    videoId: "video-ecg",
    pdfId: "pdf-ecg",
  },
  {
    id: "module-heart-failure",
    courseId: "course-cardiology",
    title: "Heart Failure & Hemodynamics",
    summary: "Preload, afterload, compensated states, and evidence-based therapy.",
    durationMinutes: 96,
    orderIndex: 2,
    completionPercent: 64,
    videoId: "video-heart-failure",
    pdfId: "pdf-heart-failure",
  },
  {
    id: "module-cranial-nerves",
    courseId: "course-neuro",
    title: "Cranial Nerves Deep Dive",
    summary: "Nuclei, lesions, reflexes, and clinical pearls.",
    durationMinutes: 82,
    orderIndex: 1,
    completionPercent: 40,
    videoId: "video-cranial-nerves",
    pdfId: "pdf-cranial-nerves",
  },
  {
    id: "module-inflammation",
    courseId: "course-pathology",
    title: "Inflammation & Repair",
    summary: "Mediators, acute vs chronic inflammation, and tissue healing.",
    durationMinutes: 68,
    orderIndex: 1,
    completionPercent: 75,
    videoId: "video-inflammation",
    pdfId: "pdf-inflammation",
  },
];

export const videos: VideoResource[] = [
  {
    id: "video-ecg",
    moduleId: "module-ecg",
    title: "ECG Interpretation Essentials",
    description: "Reading rate, rhythm, axis, intervals, and ischemic changes.",
    durationMinutes: 74,
    videoUrl: "https://example.com/videos/ecg-interpretation",
    transcript: "ECG interpretation starts with rate, rhythm, axis, intervals, and morphology.",
  },
  {
    id: "video-heart-failure",
    moduleId: "module-heart-failure",
    title: "Heart Failure & Hemodynamics",
    description: "Understand forward failure, congestion, and treatment ladders.",
    durationMinutes: 96,
    videoUrl: "https://example.com/videos/heart-failure",
    transcript: "Heart failure is a clinical syndrome caused by structural or functional impairment.",
  },
  {
    id: "video-cranial-nerves",
    moduleId: "module-cranial-nerves",
    title: "Cranial Nerves Deep Dive",
    description: "Applied neuroanatomy with lesion localization.",
    durationMinutes: 82,
    videoUrl: "https://example.com/videos/cranial-nerves",
    transcript: "Each cranial nerve has unique nuclei, exits, and common lesion patterns.",
  },
  {
    id: "video-inflammation",
    moduleId: "module-inflammation",
    title: "Inflammation & Repair",
    description: "High-yield pathology revision for mediators and chronic inflammation.",
    durationMinutes: 68,
    videoUrl: "https://example.com/videos/inflammation",
    transcript: "Acute inflammation is characterized by vascular changes and neutrophil migration.",
  },
];

export const pdfs: PdfResource[] = [
  {
    id: "pdf-ecg",
    moduleId: "module-ecg",
    title: "ECG Interpretation Cheat Sheet",
    description: "One-page algorithmic approach to ECG questions.",
    pageCount: 18,
    pdfUrl: "https://example.com/pdfs/ecg-cheat-sheet.pdf",
  },
  {
    id: "pdf-heart-failure",
    moduleId: "module-heart-failure",
    title: "Heart Failure Pharmacology Review",
    description: "Guideline-based summary of HFrEF and HFpEF therapy.",
    pageCount: 22,
    pdfUrl: "https://example.com/pdfs/heart-failure-review.pdf",
  },
  {
    id: "pdf-cranial-nerves",
    moduleId: "module-cranial-nerves",
    title: "Cranial Nerve Lesion Map",
    description: "Clinical syndromes, reflexes, and nuclei tables.",
    pageCount: 16,
    pdfUrl: "https://example.com/pdfs/cranial-nerve-lesions.pdf",
  },
  {
    id: "pdf-inflammation",
    moduleId: "module-inflammation",
    title: "Inflammation Revision Notes",
    description: "Mediators, cells, repair sequence, and exam traps.",
    pageCount: 14,
    pdfUrl: "https://example.com/pdfs/inflammation-notes.pdf",
  },
];

export const books: Book[] = [
  // PRE-CLINICAL (Foundation)
  {
    id: "book-grays",
    title: "Gray’s Anatomy for Students",
    author: "Drake, Vogl, Mitchell",
    category: "PRE-CLINICAL (Foundation)",
    subject: "Anatomy",
    edition: "Latest Edition",
    coverUrl: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&w=600&q=80",
    description: "Authoritative anatomy reference with clinical integration.",
    featured: true,
    tags: ["Core", "Classic", "Anatomy"],
  },
  {
    id: "book-moore",
    title: "Clinically Oriented Anatomy",
    author: "Moore & Dalley",
    category: "PRE-CLINICAL (Foundation)",
    subject: "Anatomy",
    edition: "Latest Edition",
    coverUrl: "https://images.unsplash.com/photo-1532012197267-da84d127e765?auto=format&fit=crop&w=600&q=80",
    description: "Highly detailed clinically oriented anatomy textbook.",
    featured: false,
    tags: ["Clinical", "Anatomy"],
  },
  {
    id: "book-chaurasia",
    title: "B.D. Chaurasia’s Human Anatomy (volumes)",
    author: "B.D. Chaurasia",
    category: "PRE-CLINICAL (Foundation)",
    subject: "Anatomy",
    edition: "Latest Edition",
    coverUrl: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=600&q=80",
    description: "Popular Indian alternative for anatomy foundation.",
    featured: false,
    tags: ["Alternative", "Anatomy"],
  },
  {
    id: "book-guyton",
    title: "Guyton & Hall Textbook of Medical Physiology",
    author: "John E. Hall",
    category: "PRE-CLINICAL (Foundation)",
    subject: "Physiology",
    edition: "14th Edition",
    coverUrl: "https://images.unsplash.com/photo-1532012197267-da84d127e765?auto=format&fit=crop&w=600&q=80",
    description: "Gold standard physiology text for fundamentals and exams.",
    featured: true,
    tags: ["Gold Standard", "Physiology"],
  },
  {
    id: "book-ganong",
    title: "Ganong’s Review of Medical Physiology",
    author: "Kim E. Barrett et al.",
    category: "PRE-CLINICAL (Foundation)",
    subject: "Physiology",
    edition: "Latest Edition",
    coverUrl: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&w=600&q=80",
    description: "Excellent review of physiology with key concepts.",
    featured: false,
    tags: ["Review", "Physiology"],
  },
  {
    id: "book-harper",
    title: "Harper’s Illustrated Biochemistry",
    author: "Victor W. Rodwell et al.",
    category: "PRE-CLINICAL (Foundation)",
    subject: "Biochemistry",
    edition: "Latest Edition",
    coverUrl: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=600&q=80",
    description: "Detailed biochemistry principles.",
    featured: true,
    tags: ["Core", "Biochemistry"],
  },
  {
    id: "book-lippincott",
    title: "Lippincott’s Biochemistry",
    author: "Denise R. Ferrier",
    category: "PRE-CLINICAL (Foundation)",
    subject: "Biochemistry",
    edition: "Latest Edition",
    coverUrl: "https://images.unsplash.com/photo-1532012197267-da84d127e765?auto=format&fit=crop&w=600&q=80",
    description: "Illustrated, exam-focused biochemistry insights.",
    featured: false,
    tags: ["Review", "Biochemistry"],
  },
  // PARA-CLINICAL (Core Concepts)
  {
    id: "book-robbins",
    title: "Robbins & Cotran Pathologic Basis of Disease",
    author: "Kumar, Abbas, Aster",
    category: "PARA-CLINICAL (Core Concepts)",
    subject: "Pathology",
    edition: "Latest Edition",
    coverUrl: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&w=600&q=80",
    description: "The gold standard for pathology.",
    featured: true,
    tags: ["Gold Standard", "Pathology"],
  },
  {
    id: "book-robbins-basic",
    title: "Basic Pathology",
    author: "Kumar, Abbas & Aster",
    category: "PARA-CLINICAL (Core Concepts)",
    subject: "Pathology",
    edition: "Latest Edition",
    coverUrl: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=600&q=80",
    description: "Short version of pathology basis.",
    featured: false,
    tags: ["Short version", "Pathology"],
  },
  {
    id: "book-goljian",
    title: "Rapid Review Pathology",
    author: "Goljian",
    category: "PARA-CLINICAL (Core Concepts)",
    subject: "Pathology",
    edition: "Latest Edition",
    coverUrl: "https://images.unsplash.com/photo-1532012197267-da84d127e765?auto=format&fit=crop&w=600&q=80",
    description: "High-yield review for rapid revision.",
    featured: false,
    tags: ["High-yield", "Pathology"],
  },
  {
    id: "book-murray",
    title: "Murray’s Medical Microbiology",
    author: "Patrick R. Murray",
    category: "PARA-CLINICAL (Core Concepts)",
    subject: "Microbiology",
    edition: "Latest Edition",
    coverUrl: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&w=600&q=80",
    description: "Comprehensive medical microbiology.",
    featured: true,
    tags: ["Core", "Microbiology"],
  },
  {
    id: "book-jawetz",
    title: "Jawetz, Melnick & Adelberg’s Medical Microbiology",
    author: "Geo. F. Brooks et al.",
    category: "PARA-CLINICAL (Core Concepts)",
    subject: "Microbiology",
    edition: "Latest Edition",
    coverUrl: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=600&q=80",
    description: "Classic text on medical microbiology.",
    featured: false,
    tags: ["Classic", "Microbiology"],
  },
  {
    id: "book-katzung",
    title: "Katzung & Trevor’s Pharmacology",
    author: "Bertram G. Katzung",
    category: "PARA-CLINICAL (Core Concepts)",
    subject: "Pharmacology",
    edition: "Latest Edition",
    coverUrl: "https://images.unsplash.com/photo-1532012197267-da84d127e765?auto=format&fit=crop&w=600&q=80",
    description: "Excellent pharmacology review and text.",
    featured: true,
    tags: ["Core", "Pharmacology"],
  },
  {
    id: "book-brunton",
    title: "Basic & Clinical Pharmacology",
    author: "Brunton",
    category: "PARA-CLINICAL (Core Concepts)",
    subject: "Pharmacology",
    edition: "Latest Edition",
    coverUrl: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&w=600&q=80",
    description: "Standard text for clinical pharmacology.",
    featured: false,
    tags: ["Clinical", "Pharmacology"],
  },
  // PARA-CLINICAL / CLINICAL TRANSITION
  {
    id: "book-reddy",
    title: "Essentials of Forensic Medicine & Toxicology",
    author: "Reddy & Murthy",
    category: "PARA-CLINICAL / CLINICAL TRANSITION",
    subject: "Forensic Medicine & Toxicology (FMT)",
    edition: "Latest Edition",
    coverUrl: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=600&q=80",
    description: "Comprehensive forensic medicine and toxicology.",
    featured: true,
    tags: ["FMT", "Forensic", "Toxicology"],
  },
  {
    id: "book-narayan-reddy",
    title: "Textbook of Forensic Medicine",
    author: "K.S. Narayan Reddy",
    category: "PARA-CLINICAL / CLINICAL TRANSITION",
    subject: "Forensic Medicine & Toxicology (FMT)",
    edition: "Latest Edition",
    coverUrl: "https://images.unsplash.com/photo-1532012197267-da84d127e765?auto=format&fit=crop&w=600&q=80",
    description: "Alternative textbook of forensic medicine.",
    featured: false,
    tags: ["Alternative", "FMT"],
  },
  {
    id: "book-park",
    title: "Park’s Textbook of Preventive & Social Medicine",
    author: "K. Park",
    category: "PARA-CLINICAL / CLINICAL TRANSITION",
    subject: "PSM (Preventive & Social Medicine)",
    edition: "Latest Edition",
    coverUrl: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&w=600&q=80",
    description: "The gold standard for preventive and social medicine.",
    featured: true,
    tags: ["Core", "PSM", "Community Medicine"],
  },
  // CLINICAL CORE
  {
    id: "book-harrison",
    title: "Harrison's Principles of Internal Medicine",
    author: "J. Larry Jameson",
    category: "CLINICAL CORE",
    subject: "Medicine",
    edition: "21st Edition",
    coverUrl: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=600&q=80",
    description: "Comprehensive medicine text with system-wise disease reviews.",
    featured: true,
    tags: ["Medicine", "Clinical"],
  },
  {
    id: "book-stepup",
    title: "Step-Up to Medicine / Pocket Medicine",
    author: "Various",
    category: "CLINICAL CORE",
    subject: "Medicine",
    edition: "Latest Edition",
    coverUrl: "https://images.unsplash.com/photo-1532012197267-da84d127e765?auto=format&fit=crop&w=600&q=80",
    description: "Exam-friendly and quick review for medicine.",
    featured: false,
    tags: ["Exam-friendly", "Medicine"],
  },
  {
    id: "book-schwartz",
    title: "Schwartz’s Principles of Surgery",
    author: "F. Charles Brunicardi",
    category: "CLINICAL CORE",
    subject: "Surgery",
    edition: "Latest Edition",
    coverUrl: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&w=600&q=80",
    description: "Comprehensive surgical principles.",
    featured: true,
    tags: ["Surgery", "Core"],
  },
  {
    id: "book-bailey",
    title: "Bailey & Love’s Short Practice of Surgery",
    author: "Norman Williams et al.",
    category: "CLINICAL CORE",
    subject: "Surgery",
    edition: "Latest Edition",
    coverUrl: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=600&q=80",
    description: "Classic text focusing on standard practice of surgery.",
    featured: false,
    tags: ["Classic", "Surgery"],
  },
  {
    id: "book-williams-ob",
    title: "Williams Obstetrics",
    author: "F. Gary Cunningham et al.",
    category: "CLINICAL CORE",
    subject: "Obstetrics & Gynecology",
    edition: "Latest Edition",
    coverUrl: "https://images.unsplash.com/photo-1532012197267-da84d127e765?auto=format&fit=crop&w=600&q=80",
    description: "Gold standard reference for obstetrics.",
    featured: true,
    tags: ["Obstetrics", "OBGYN"],
  },
  {
    id: "book-dutta",
    title: "Dutta’s Textbook of Obstetrics",
    author: "D.C. Dutta",
    category: "CLINICAL CORE",
    subject: "Obstetrics & Gynecology",
    edition: "Latest Edition",
    coverUrl: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&w=600&q=80",
    description: "Very widely read and student-friendly text.",
    featured: false,
    tags: ["Obstetrics"],
  },
  {
    id: "book-williams-gyn",
    title: "Williams Gynecology / Shaw’s Textbook of Gynecology",
    author: "Hoffman et al.",
    category: "CLINICAL CORE",
    subject: "Obstetrics & Gynecology",
    edition: "Latest Edition",
    coverUrl: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=600&q=80",
    description: "Extensive text detailing gynecological practices.",
    featured: false,
    tags: ["Gynecology"],
  },
  // SPECIALTY CLINICAL
  {
    id: "book-cummings",
    title: "Cummings Otolaryngology — Head & Neck Surgery",
    author: "Paul W. Flint et al.",
    category: "SPECIALTY CLINICAL",
    subject: "ENT (Otorhinolaryngology)",
    edition: "Latest Edition",
    coverUrl: "https://images.unsplash.com/photo-1532012197267-da84d127e765?auto=format&fit=crop&w=600&q=80",
    description: "Foremost text on ENT and head & neck surgery.",
    featured: true,
    tags: ["ENT", "Surgery"],
  },
  {
    id: "book-ent-glance",
    title: "ENT at a Glance",
    author: "Nazia Munir et al.",
    category: "SPECIALTY CLINICAL",
    subject: "ENT (Otorhinolaryngology)",
    edition: "Latest Edition",
    coverUrl: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&w=600&q=80",
    description: "Rapid review of ENT.",
    featured: false,
    tags: ["Review", "ENT"],
  },
  {
    id: "book-parsons",
    title: "Parson’s Diseases of the Eye",
    author: "Sihota & Tandon",
    category: "SPECIALTY CLINICAL",
    subject: "Ophthalmology",
    edition: "Latest Edition",
    coverUrl: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=600&q=80",
    description: "Core textbook for ophthalmic study.",
    featured: true,
    tags: ["Ophthalmology"],
  },
  {
    id: "book-vaughan",
    title: "Vaughan & Asbury’s General Ophthalmology",
    author: "Paul Riordan-Eva",
    category: "SPECIALTY CLINICAL",
    subject: "Ophthalmology",
    edition: "Latest Edition",
    coverUrl: "https://images.unsplash.com/photo-1532012197267-da84d127e765?auto=format&fit=crop&w=600&q=80",
    description: "Essentials for general ophthalmology.",
    featured: false,
    tags: ["Essentials", "Ophthalmology"],
  },
  {
    id: "book-campbell",
    title: "Campbell’s Operative Orthopaedics",
    author: "Frederick M. Azar et al.",
    category: "SPECIALTY CLINICAL",
    subject: "Orthopedics",
    edition: "Latest Edition",
    coverUrl: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&w=600&q=80",
    description: "Unparalleled resource on operative orthopedics.",
    featured: true,
    tags: ["Orthopedics", "Surgery"],
  },
  {
    id: "book-saha",
    title: "Orthopaedics, Trauma & Rheumatology",
    author: "A.K. Saha",
    category: "SPECIALTY CLINICAL",
    subject: "Orthopedics",
    edition: "Latest Edition",
    coverUrl: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=600&q=80",
    description: "Thorough textbook for orthopedics and trauma.",
    featured: false,
    tags: ["Textbook", "Orthopaedics"],
  },
  {
    id: "book-miller",
    title: "Miller’s Anesthesia",
    author: "Michael A. Gropper",
    category: "SPECIALTY CLINICAL",
    subject: "Anesthesia",
    edition: "Latest Edition",
    coverUrl: "https://images.unsplash.com/photo-1532012197267-da84d127e765?auto=format&fit=crop&w=600&q=80",
    description: "Definitive text for anesthesia principles.",
    featured: true,
    tags: ["Anesthesia"],
  },
  {
    id: "book-stoelting",
    title: "Stoelting’s Pharmacology & Physiology in Anesthetic Practice",
    author: "Pamela Flood et al.",
    category: "SPECIALTY CLINICAL",
    subject: "Anesthesia",
    edition: "Latest Edition",
    coverUrl: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&w=600&q=80",
    description: "Clinical basics for anesthetic pharmacology and physiology.",
    featured: false,
    tags: ["Clinical", "Anesthesia"],
  },
  {
    id: "book-kaplan",
    title: "Kaplan & Sadock’s Synopsis of Psychiatry",
    author: "Benjamin J. Sadock et al.",
    category: "SPECIALTY CLINICAL",
    subject: "Psychiatry",
    edition: "Latest Edition",
    coverUrl: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=600&q=80",
    description: "Extensive resource on behavioral sciences and psychiatry.",
    featured: true,
    tags: ["Psychiatry", "Behavioral"],
  },
  {
    id: "book-kulhara",
    title: "Textbook of Psychiatry",
    author: "Kulhara / Trzepacz & Baker",
    category: "SPECIALTY CLINICAL",
    subject: "Psychiatry",
    edition: "Latest Edition",
    coverUrl: "https://images.unsplash.com/photo-1532012197267-da84d127e765?auto=format&fit=crop&w=600&q=80",
    description: "Alternative learning structure for psychiatry text.",
    featured: false,
    tags: ["Alternative", "Psychiatry"],
  },
];

export const quizzes: Quiz[] = [
  {
    id: "quiz-cardiology",
    title: "Cardiovascular Systems Drill",
    description: "Timed practice focused on cardiology concepts and clinical reasoning.",
    subject: "Medicine",
    examTrack: "NEET_PG",
    durationMinutes: 85,
    totalQuestions: 6,
    difficulty: "hard",
    topicFocus: ["Cardiac cycle", "Heart sounds", "Shock", "Valvular disease"],
  },
  {
    id: "quiz-pathology",
    title: "Inflammation & Repair Sprint",
    description: "Rapid pathology revision with explanation-first feedback.",
    subject: "Pathology",
    examTrack: "MBBS",
    durationMinutes: 35,
    totalQuestions: 4,
    difficulty: "medium",
    topicFocus: ["Inflammation", "Mediators", "Repair"],
  },
  {
    id: "quiz-usmle-pulm",
    title: "USMLE Pulmonology High-Yield MCQs",
    description: "Step-style question set on respiratory disease and physiology.",
    subject: "Medicine",
    examTrack: "USMLE",
    durationMinutes: 45,
    totalQuestions: 4,
    difficulty: "hard",
    topicFocus: ["Pneumonia", "ARDS", "Ventilator settings"],
  },
];

export const questions: Question[] = [
  {
    id: "q1",
    quizId: "quiz-cardiology",
    subject: "Medicine",
    topic: "Cardiac cycle",
    prompt: "Which of the following events occurs during isovolumetric contraction?",
    explanation:
      "Both the mitral and aortic valves are closed, so ventricular pressure rises without a change in volume.",
    difficulty: "medium",
    correctOptionId: "q1-b",
    options: [
      { id: "q1-a", label: "A", text: "Rapid ventricular filling" },
      { id: "q1-b", label: "B", text: "Rise in ventricular pressure at constant volume" },
      { id: "q1-c", label: "C", text: "Opening of semilunar valves" },
      { id: "q1-d", label: "D", text: "Atrial contraction" },
    ],
  },
  {
    id: "q2",
    quizId: "quiz-cardiology",
    subject: "Medicine",
    topic: "Valvular disease",
    prompt: "A mid-diastolic murmur with opening snap is most suggestive of:",
    explanation: "The classic auscultatory finding is mitral stenosis.",
    difficulty: "easy",
    correctOptionId: "q2-a",
    options: [
      { id: "q2-a", label: "A", text: "Mitral stenosis" },
      { id: "q2-b", label: "B", text: "Aortic regurgitation" },
      { id: "q2-c", label: "C", text: "Mitral regurgitation" },
      { id: "q2-d", label: "D", text: "Aortic stenosis" },
    ],
  },
  {
    id: "q3",
    quizId: "quiz-cardiology",
    subject: "Medicine",
    topic: "Shock",
    prompt: "The most likely hemodynamic profile in septic shock is:",
    explanation:
      "Septic shock typically presents with reduced systemic vascular resistance and elevated cardiac output in the warm phase.",
    difficulty: "hard",
    correctOptionId: "q3-c",
    options: [
      { id: "q3-a", label: "A", text: "High SVR, low cardiac output" },
      { id: "q3-b", label: "B", text: "High SVR, high cardiac output" },
      { id: "q3-c", label: "C", text: "Low SVR, high cardiac output" },
      { id: "q3-d", label: "D", text: "Normal SVR, low preload" },
    ],
  },
  {
    id: "q4",
    quizId: "quiz-cardiology",
    subject: "Medicine",
    topic: "Heart sounds",
    prompt: "A fixed split S2 is classically associated with:",
    explanation: "Atrial septal defect causes fixed splitting of the second heart sound.",
    difficulty: "medium",
    correctOptionId: "q4-d",
    options: [
      { id: "q4-a", label: "A", text: "Pulmonary hypertension" },
      { id: "q4-b", label: "B", text: "Aortic stenosis" },
      { id: "q4-c", label: "C", text: "Mitral valve prolapse" },
      { id: "q4-d", label: "D", text: "Atrial septal defect" },
    ],
  },
  {
    id: "q5",
    quizId: "quiz-cardiology",
    subject: "Medicine",
    topic: "Cardiac cycle",
    prompt: "The a wave in the jugular venous pulse corresponds to:",
    explanation: "The a wave reflects right atrial contraction.",
    difficulty: "easy",
    correctOptionId: "q5-b",
    options: [
      { id: "q5-a", label: "A", text: "Ventricular systole" },
      { id: "q5-b", label: "B", text: "Atrial contraction" },
      { id: "q5-c", label: "C", text: "Opening of the tricuspid valve" },
      { id: "q5-d", label: "D", text: "Venous filling of the atrium" },
    ],
  },
  {
    id: "q6",
    quizId: "quiz-cardiology",
    subject: "Medicine",
    topic: "Heart failure",
    prompt: "Which drug class has a proven mortality benefit in HFrEF?",
    explanation: "ACE inhibitors, beta blockers, MRAs, and SGLT2 inhibitors improve survival in HFrEF.",
    difficulty: "medium",
    correctOptionId: "q6-c",
    options: [
      { id: "q6-a", label: "A", text: "Loop diuretics alone" },
      { id: "q6-b", label: "B", text: "Digoxin alone" },
      { id: "q6-c", label: "C", text: "ACE inhibitors" },
      { id: "q6-d", label: "D", text: "Nitrates only" },
    ],
  },
  {
    id: "q7",
    quizId: "quiz-pathology",
    subject: "Pathology",
    topic: "Inflammation",
    prompt: "The first cells to arrive in acute inflammation are usually:",
    explanation: "Neutrophils dominate the early phase of acute inflammation.",
    difficulty: "easy",
    correctOptionId: "q7-a",
    options: [
      { id: "q7-a", label: "A", text: "Neutrophils" },
      { id: "q7-b", label: "B", text: "Lymphocytes" },
      { id: "q7-c", label: "C", text: "Eosinophils" },
      { id: "q7-d", label: "D", text: "Fibroblasts" },
    ],
  },
  {
    id: "q8",
    quizId: "quiz-pathology",
    subject: "Pathology",
    topic: "Repair",
    prompt: "Granulation tissue is characterized by:",
    explanation: "Granulation tissue contains proliferating capillaries and fibroblasts.",
    difficulty: "medium",
    correctOptionId: "q8-d",
    options: [
      { id: "q8-a", label: "A", text: "Dense collagen and scarce vessels" },
      { id: "q8-b", label: "B", text: "Hyalinized scar only" },
      { id: "q8-c", label: "C", text: "Caseous necrosis" },
      { id: "q8-d", label: "D", text: "New capillaries and fibroblasts" },
    ],
  },
  {
    id: "q9",
    quizId: "quiz-usmle-pulm",
    subject: "Medicine",
    topic: "Pneumonia",
    prompt: "The most common cause of community-acquired pneumonia is:",
    explanation: "Streptococcus pneumoniae remains the most common cause of typical CAP.",
    difficulty: "medium",
    correctOptionId: "q9-a",
    options: [
      { id: "q9-a", label: "A", text: "Streptococcus pneumoniae" },
      { id: "q9-b", label: "B", text: "Mycoplasma pneumoniae" },
      { id: "q9-c", label: "C", text: "Haemophilus influenzae" },
      { id: "q9-d", label: "D", text: "Staphylococcus aureus" },
    ],
  },
  {
    id: "q10",
    quizId: "quiz-usmle-pulm",
    subject: "Medicine",
    topic: "ARDS",
    prompt: "A key pathologic feature of ARDS is:",
    explanation: "Diffuse alveolar damage with hyaline membrane formation defines ARDS.",
    difficulty: "hard",
    correctOptionId: "q10-b",
    options: [
      { id: "q10-a", label: "A", text: "Pleural fibrosis" },
      { id: "q10-b", label: "B", text: "Diffuse alveolar damage" },
      { id: "q10-c", label: "C", text: "Bronchial smooth muscle hypertrophy" },
      { id: "q10-d", label: "D", text: "Caseating granulomas" },
    ],
  },
];

export const quizAttempts: QuizAttempt[] = [
  {
    id: "attempt-cardiology-1",
    quizId: "quiz-cardiology",
    userId: "user-sarah",
    status: "submitted",
    startedAt: "2026-03-21T06:00:00.000Z",
    submittedAt: "2026-03-21T07:04:00.000Z",
    timeSpentSeconds: 3840,
    score: 83,
    accuracy: 83,
    answers: [
      { questionId: "q1", optionId: "q1-b", markedForReview: false, eliminatedOptionIds: [] },
      { questionId: "q2", optionId: "q2-a", markedForReview: false, eliminatedOptionIds: [] },
      { questionId: "q3", optionId: "q3-c", markedForReview: true, eliminatedOptionIds: ["q3-b"] },
      { questionId: "q4", optionId: "q4-d", markedForReview: false, eliminatedOptionIds: [] },
      { questionId: "q5", optionId: "q5-d", markedForReview: false, eliminatedOptionIds: [] },
      { questionId: "q6", optionId: "q6-c", markedForReview: false, eliminatedOptionIds: [] },
    ],
  },
];

export const progressSnapshots: ProgressSnapshot[] = [
  {
    userId: "user-sarah",
    completedCourses: 4,
    completionPercent: 72,
    hoursLearned: 126,
    quizzesTaken: 38,
    averageAccuracy: 78,
    weakTopics: ["Cardiac cycle", "Ventilator settings", "Acid-base disorders"],
    strongTopics: ["Neuroanatomy", "Antibiotics", "Inflammation"],
  },
];

export const analyticsInsights: AnalyticsInsight[] = [
  { label: "Accuracy", value: 78, trend: 6 },
  { label: "Study Hours", value: 12.4, trend: 8 },
  { label: "Quiz Velocity", value: 42, trend: -5 },
  { label: "Revision Consistency", value: 88, trend: 12 },
];

export const studyTasks: StudyTask[] = [
  {
    id: "task-1",
    userId: "user-sarah",
    title: "Review Physiology",
    description: "Cardiac cycle and pressure-volume loops",
    scheduledFor: "2026-03-25T04:00:00.000Z",
    status: "todo",
    category: "revision",
  },
  {
    id: "task-2",
    userId: "user-sarah",
    title: "15 MCQs in Pathology",
    description: "Focus on neoplasia and inflammation",
    scheduledFor: "2026-03-25T06:30:00.000Z",
    status: "in_progress",
    category: "quiz",
  },
  {
    id: "task-3",
    userId: "user-sarah",
    title: "Watch ECG Lecture",
    description: "Module 4: Arrhythmias and conduction blocks",
    scheduledFor: "2026-03-25T09:30:00.000Z",
    status: "todo",
    category: "course",
  },
];

export const studyPlan: StudyPlan = {
  date: "2026-03-25",
  tasks: studyTasks,
};

export const notifications: UserNotification[] = [
  {
    id: "notif-1",
    userId: "user-sarah",
    title: "Mock NEET PG Simulation",
    message: "Your full-length simulation starts Saturday at 9:00 AM.",
    type: "quiz",
    createdAt: "2026-03-24T11:00:00.000Z",
    read: false,
  },
  {
    id: "notif-2",
    userId: "user-sarah",
    title: "AI Recommendation Ready",
    message: "Cardiac cycle and ventilator settings were added to your focus stack.",
    type: "recommendation",
    createdAt: "2026-03-24T08:20:00.000Z",
    read: true,
  },
];

export const notes: Note[] = [
  {
    id: "note-1",
    userId: "user-sarah",
    moduleId: "module-heart-failure",
    content: "S3 is a sign of volume overload. Distinguish HFrEF vs HFpEF therapy tables.",
    createdAt: "2026-03-22T10:30:00.000Z",
  },
];

export const recommendations: AIRecommendation[] = [
  {
    id: "rec-1",
    userId: "user-sarah",
    title: "Rebuild your cardiac cycle foundation",
    description: "You miss pressure-volume and valve timing questions under time pressure.",
    topic: "Cardiac cycle",
    priority: "high",
  },
  {
    id: "rec-2",
    userId: "user-sarah",
    title: "Schedule a 20-minute ventilator revision",
    description: "USMLE-style respiratory support questions are trending below your baseline.",
    topic: "Ventilator settings",
    priority: "medium",
  },
  {
    id: "rec-3",
    userId: "user-sarah",
    title: "Lean into neuroanatomy momentum",
    description: "Your strongest recall window is in anatomy. Convert it into spaced revision.",
    topic: "Neuroanatomy",
    priority: "low",
  },
];

export const assistantConversation: ChatMessage[] = [
  {
    id: "msg-1",
    role: "assistant",
    content:
      "You’ve been strongest in anatomy this week. If we focus on cardiac cycle today, I can generate a 25-minute revision block plus 10 custom MCQs.",
    createdAt: "2026-03-25T05:00:00.000Z",
  },
  {
    id: "msg-2",
    role: "user",
    content: "Why is isovolumetric contraction tested so often?",
    createdAt: "2026-03-25T05:01:00.000Z",
  },
];

export const dashboardPayload: DashboardPayload = {
  user: users[0],
  progress: progressSnapshots[0],
  recommendations,
  courses,
  planner: studyPlan,
  notifications,
};
